name: Build Magisk module

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r28-beta2-linux.zip
        unzip android-ndk-r28-beta2-linux.zip
    - name: Build
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: magisk-overlayfs-release
        path: out/magisk-module
